### ISSUE TITLE
Error: can't find file './text_map_setter'

### ISSUE THREAD

**Issue by stakach** [wyhaines/opentelemetry-api.cr#2]
https://github.com/wyhaines/opentelemetry-api.cr/blob/main/src/opentelemetry-api/propagation/trace_context.cr#L3

In the latest release

**Comment by wyhaines** [comment]
Is that in the release or in main? I think that I pushed a broken build to
main right before I had to travel today, and I have not had a chance to go
fix it yet.


Kirk Haines

**Comment by stakach** [comment]
in the release, I see the error when adding this to my shard.yml

<img width="241" alt="image" src="https://user-images.githubusercontent.com/368013/165421032-4300bdfd-0a43-4a32-aa1b-df842311cb74.png">

**Comment by wyhaines** [comment]
OK. That truly surprises me. I will resolve it asap


Thanks,

Kirk Haines

**Comment by stakach** [comment]
This would be the culprit
https://github.com/wyhaines/opentelemetry-instrumentation.cr/blob/main/shard.yml#L16

**Comment by wyhaines** [comment]
I fixed the shard.yml file so that it doesn't point to main.
